@extends('layouts.panel')
@section('title','تصميم المنيو')
@section('content')
<div class="settings-heading"><div><span class="eyebrow text-primary">مصمم المنيو</span><h1>تصميم: {{ $menuPage->name }}</h1><p class="text-muted">خصص الألوان والخطوط وشكل العرض بما يناسب علامتك.</p></div><a class="btn btn-outline-primary" target="_blank" href="{{ $menuPage->is_default?route('public.restaurant',$menuPage->restaurant):route('public.menu',[$menuPage->restaurant,$menuPage]) }}"><i class="bi bi-eye"></i> معاينة</a></div>
<form method="post" action="{{ route('dashboard.theme.update',$menuPage) }}">@csrf @method('put')
<div class="card p-4 mb-4"><h2 class="settings-section-title"><i class="bi bi-palette"></i> الألوان</h2><div class="theme-colors">@foreach(['primary_color'=>['الأساسي','#7c3aed'],'secondary_color'=>['الثانوي','#35205a'],'background_color'=>['الخلفية','#f8f7fc'],'card_background_color'=>['البطاقة','#ffffff'],'text_color'=>['النص','#211d2c'],'heading_color'=>['العناوين','#17131f'],'price_color'=>['السعر','#7c3aed'],'button_color'=>['الأزرار','#7c3aed'],'border_color'=>['الحدود','#ebe7f1']] as $key=>[$label,$fallback])<label class="theme-color-field"><span>{{ $label }}</span><div><input type="color" name="{{ $key }}" value="{{ old($key,$menuPage->theme->$key?:$fallback) }}"><code>{{ old($key,$menuPage->theme->$key?:$fallback) }}</code></div></label>@endforeach</div></div>
<div class="row g-4"><div class="col-xl-6"><div class="card p-4 h-100"><h2 class="settings-section-title"><i class="bi bi-grid"></i> التخطيط والبطاقات</h2><div class="row g-3">@foreach([
'layout_type'=>['التخطيط',['grid'=>'شبكة','list'=>'قائمة']],'category_layout'=>['التصنيفات',['tabs'=>'تبويبات','pills'=>'شرائح','buttons'=>'أزرار']],'item_card_style'=>['البطاقة',['vertical'=>'رأسية','horizontal'=>'أفقية','minimal'=>'بسيطة']],'image_position'=>['مكان الصورة',['top'=>'أعلى','right'=>'يمين','left'=>'يسار']],'image_shape'=>['شكل الصورة',['rounded'=>'دائرية الحواف','square'=>'مربعة','circle'=>'دائرة']],'card_shadow'=>['الظل',['none'=>'بدون','soft'=>'خفيف','medium'=>'متوسط','strong'=>'قوي']],'content_width'=>['عرض المحتوى',['960px'=>'ضيق','1140px'=>'متوسط','1320px'=>'واسع','100%'=>'كامل']]] as $key=>[$label,$options])<div class="col-md-6"><label class="form-label">{{ $label }}</label><select class="form-select" name="{{ $key }}">@foreach($options as $value=>$text)<option value="{{ $value }}" @selected(($menuPage->theme->$key?:array_key_first($options))===$value)>{{ $text }}</option>@endforeach</select></div>@endforeach<div class="col-12"><label>استدارة الحواف</label><input class="form-range" type="range" name="card_border_radius" min="0" max="40" value="{{ $menuPage->theme->card_border_radius }}"></div></div></div></div>
<div class="col-xl-6"><div class="card p-4 h-100"><h2 class="settings-section-title"><i class="bi bi-fonts"></i> الخطوط والعرض</h2><div class="row g-3">@foreach(['font_family'=>'خط النص','heading_font_family'=>'خط العناوين'] as $key=>$label)<div class="col-md-6"><label class="form-label">{{ $label }}</label><select class="form-select" name="{{ $key }}">@foreach(['Tahoma','Arial','Cairo','Tajawal','system-ui'] as $font)<option @selected(($menuPage->theme->$key?:'Tahoma')===$font)>{{ $font }}</option>@endforeach</select></div>@endforeach @foreach(['items_per_row_desktop'=>['أعمدة الكمبيوتر',4],'items_per_row_tablet'=>['أعمدة التابلت',3],'items_per_row_mobile'=>['أعمدة الهاتف',2]] as $key=>[$label,$max])<div class="col-md-4"><label class="form-label">{{ $label }}</label><input class="form-control" type="number" name="{{ $key }}" min="1" max="{{ $max }}" value="{{ $menuPage->theme->$key }}"></div>@endforeach</div><h2 class="settings-section-title mt-4"><i class="bi bi-toggles"></i> عناصر العرض</h2><div class="theme-switches">@foreach(['show_item_images'=>'صور الأصناف','show_descriptions'=>'الوصف','show_prices'=>'الأسعار','show_category_images'=>'صور التصنيفات','sticky_categories'=>'تثبيت التصنيفات','enable_search'=>'البحث','enable_category_filter'=>'فلترة التصنيفات','enable_dark_mode'=>'الوضع الداكن'] as $key=>$label)<label class="form-check form-switch"><input class="form-check-input" type="checkbox" name="{{ $key }}" value="1" @checked($menuPage->theme->$key)><span>{{ $label }}</span></label>@endforeach</div></div></div></div>
<div class="settings-actions mt-4"><button class="btn btn-primary btn-lg px-5"><i class="bi bi-check2-circle"></i> حفظ التصميم</button></div></form>
@endsection
